name: create_container
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/create_container.yml'
      - './weather-app/*'
jobs:
  docker_image_build:
    defaults:
      run:
        working-directory: ./weather-project/weather-app
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # environment:
    #   name: approval
    env:
      STAGE_FILE: "docker-compose.container.yml"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      USERNAME: ${{ secrets.USERNAME }}
    steps:
    - uses: actions/checkout@v2
    - name: Log into ECR
      run: make login_ecr
    - name: Create Docker image
      run: make build_docker
    - name: Push Docker image
      run: make push_image