name: destroy
on:
  workflow_dispatch:
  push:
    branches:
      - destroy
    paths:
      - '.github/workflows/destroy-image.yml'
      - './weather-app/'
jobs:
  docker_image_build:
    defaults:
      run:
        working-directory: ./weather-app
    runs-on: ubuntu-latest
    env:
      STAGE_FILE: "docker-compose.container.yml"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
    steps:
    - uses: actions/checkout@v2
    - name: Log into ECR
      run: make login_ecr
    - name: Destroy Docker image
      run: make destroy_image